### ISSUE TITLE
Which 13.3" screen?

### ISSUE THREAD

**Issue by vdp** [Modos-Labs/Glider#3]
Hi Wenting,
I notice that you seem to be hard at work with the Caster and Glider repos, and I'm eagerly awaiting the moment when the projects will be pronounced suitable for early adopters. I'm guessing that you will be holding back such announcements at least until Alex Soto's FOSDEM presentations next week, so although there are many things I'd like to ask about the availability of the hardware, I will wait patiently for a few more days :)

The thing I'd like to ask now, if you have a spare minute, is about the screens. I have a few 6" screens, as well as ES108FC1(which I'm yet to make proper adapter for), but I'm looking into buying a 13.3" one. I know that you get to see many different screens, so I'd like to tap into that experience, and ask for a recommendation which one of the screens available on AliExpress to buy. Currently the screens for sale I see are:

- ES133UT1 (1600x1200)
- ES133UT2 (1600x1200)
- ES133TT3 (2200×1650)

What I'm most interested in, is the clarity of the screen, i.e. which one is most readable. I would prefer screen without too "aggressive" anti-glare coating because from experience this makes them substantially blurrier in low-light conditions. I think the glass substrate screens have a bit better image quality, but unfortunately at the moment no ED133's seem to be on offer...

Do you have experience with the above screens? I realize you likely don't have time to make extensive comparisons, so I'm just asking about your impressions and advice if you have any to share.

Sorry for opening an issue with a question that's only tangentially related to Glider, but I just don't know if there is a better way to reach you.

Thanks!

**Comment by zephray** [comment]
Personally, I have used both UT1 and UT2. However, I didn't notice much difference in terms of the clarity, both of them have a similar anti-glare surface finish. I know some of the glass substrate screens have a glossy finish (such as the ED060XC8), but I don't know if this is the case with ED133 screens. UT2 (Carta) does offer a better contrast ratio and faster response than UT1 (Pearl), TT3 should be similar to UT2. In terms of compatibility with Glider and Caster, UT2 is the recommended model for now. The current error-diffusion dithering unit is limited to about 133MP/s on Spartan-6 devices. This pretty much limits the maximum resolution to 1600x1200/ 1920x1080 (at 60Hz). The dithering unit to be honest doesn't need to run at 60Hz, so in the future, I should be able to run it at 30Hz and remove this limitation. In that case, the pixel rate limit is 224MP/s by the 2-lane DisplayPort HBR bandwidth, which is just barely enough for 2200x1650 at 60Hz. So supporting TT3 is possible with the hardware but not currently supported, UT2 works out of the box.

**Comment by vdp** [comment]
Thank you!

This is just the info that I was hoping for. UT2 looks like the best/safest choice for now indeed, so that's what I will be buying. Moreover, I'd like to be able to use Glider(assuming I can lay my hands on it in the first place :) with older PCs that don't have video over usb-c capabilities. I'm still learning about video interfaces, and this stuff is a bit over my head right now, to be honest, so I wonder what the maximum pixel rate would be with the DVI input? If it's limited to single-link DVI speeds, that will once again limit the resolution to FullHD/UXGA@60Hz.

**Comment by zephray** [comment]
The DVI input pixel rate is currently limited to 105MP/s as the FPGA's deserializer is only rated to 1.05Gbps. This is also the reason why I didn't implement the DVI initially, it's a bit slow. This means something around 1080p/UXGA@50Hz. It's also possible to overclock the FPGA a bit to 125MP/s, it generally works but not guaranteed. In the future, if HDMI protocol is implemented (rather than just using the plain DVI protocol), then the pixel rate can be doubled to 210MP/s with YUV420 chroma subsampling (actually I don't need any color but HDMI/DVI doesn't offer any monochrome mode, so chroma subsampling is the second best thing to do)

**Comment by vdp** [comment]
That's good to know, thanks! 50Hz would be quite alright I think, though it will probably require slight tweaking to the EPD waveforms/per-pixel counters(assuming the pixel state is still like the early version I've studied briefly an year or so ago) to account for the coarser update intervals. 

In my specific case, the machines I'm thinking about actually do have DP(or mini DP) ports, so in principle it would be possible to use DP to USB-C adapters. I think some sort of powered adapter will be needed such as [this one]( https://www.amazon.com/WJESOG-DisplayPort-Adapter-Converter-Thunderbolt/dp/B0BNX7MS6N), because of the large discrepancy between the current ratings for both protocols. How much power is the Glider(lite, I guess?) supposed to draw? I mean would a USB 3.0 port (Google says 900mA/4.5W) be good enough?

And if the HDMI port is to be used an USB-C cable will probably still be needed to provide VBUS?

**Comment by zephray** [comment]
Actually, just forget about that 50Hz limitation. I decided to just add an ADV7611 for HDMI/DVI RX, and that's rated up to 162MP/s. The issue is that the FPGA couldn't do any equalization to the TMDS signal, so it is going to be quite sensitive to the cable quality. If I want to feed the HDMI/DVI signal directly into the FPGA, I need to add a dedicated equalizer/redriver/retimer chip. Turns out in terms of the cost, it's quite close to the cost of adding an ADV7611 (which has all these compensation circuits built in). As a result I am going with the 7611 instead. This would even allow me to do 80Hz refresh (Eink's vendor waveforms are usually designed to run at 85Hz so it's better to run the controller close to that).

The Glider Lite draws about 1W continuously, the final version with both PTN3460 and ADV7611 for DP and HDMI input would draw more power, probably looking at around 1.5W. In either case a USB 3.0 port should be good enough.

Yes you are correct that if the HDMI port is to be used, an USB-C cable will still be required to provide VBUS. The 5V on the HDMI is only rated for up to 50mA IIRC.

**Comment by vdp** [comment]
I'm very glad to heart that, though I'd imagine it would be a hassle and really a bit of a shame to change the so nicely laid out schematic and PCB. I was actually thumbing through ADV7611's documentation myself[*] and I'm impressed by the configurability and observability offered by this chip, no wonder it's so popular. And it would not require much more FPGA pins, I think: LLC+HS+VS+8-bit Y input(and perhaps optionally an interrupt line). IIRC the function of the output pins is actually configurable + the user can mix, scale and offset the inputs to produce output however they like in the so called CP block.

1.5W sounds great. I guess this is for the board itself, i.e. not taking into account the EPD panel? IIRC the panels can consume more than 1.5W when updating. Speaking of which, may I ask why did you decide not to use a PMIC such as TPS651851? Is it done for future proofing the design, for e.g. larger screens, or is the *1 version once again scarce(last time I looked a few months ago the supply seem to have recovered)?


[*] I'm tinkering with a design of mine that uses a module from a certain Chinese FPGA vendor which shall remain unnamed lest some guy pop up here, as in a previous GH conversation and I'm once again accused to being a CCP shill or whatever(with messages in Chinese no less :) That was actually funny). That board, is both a bit of a mess and complete overkill with many solder jumpers to configure e.g. 1v8/3v3 power for the ADV7611. I just barely know what I'm doing, so to be on the safe side made the thing so that it can be configured to use TMI7003C(a neat 3-output DC-DC chip I lifted from Sipeed's design), TMI7003C + 2 LDOs to post-filter the power if needed, or just the 2 LDOs by themselves. Anyway, that PCB was never meant to be anything more than a way for me to learn, and I don't even know yet if it works at all. I'm very much looking forward to Glider/Caster which are on an entirely different level(not to mention I haven't even started writing the gateware).

**Comment by zephray** [comment]
Yeah it's a quite versatile chip. I am still thinking of routing all signal lines into the FPGA, just kind of to be future-proof once I start working with color panels again.

The 1.5W figure is including the EPD panel. The EPD panel consumes way more than 1.5W during peak, but on average it's quite low. Future-proofing is one part, many high resolution screens are already exceeding the capability of TPS651851. Using individual DCDCs provides higher current at a lower cost (at the expense of larger area). They could also be more efficient (TPS651851's integrated power switch has a rather high internal resistance)

Yeah that guy... Sorry about that, I should spend some time to write up some code of conduct or some sort. I hoped that I don't need that.

**Comment by vdp** [comment]
> I should spend some time to write up some code of conduct or some sort

No, no need to be sorry at all! I was referring to that episode more jokingly than anything else. I really found it rather amusing, and I don't even begrudge the guy. Perhaps he had some previous experiences that made him suspicious, and the use of Chinese was perhaps his way of "hedging" in the off-chance I turn out not to be a troll after all(in which case I wouldn't know the language; it might have even worked 10 or 15 years ago, but today machine translation is decent enough). In any case I don't think you should worry about codes of conduct and such like at least for now...

I will be closing this ticket for now. Thank you for taking time to answer my questions. It was really helpful and informative. I will be waiting for announcements from you and Alex(and possibly other Modos members I don't know about). I expect it could be months before the new version of the board that features ADV7611 is produced and tested. I only tinker with electronics projects intermittently and on a purely hobbyist level, but I can already appreciate how much time and patience is needed to bring something like this to fruition. Thank you all for doing this- it's a very significant contribution to the open source e-paper efforts.
